on:
  schedule:
    - cron: "0 0 * * *"
  push:
  workflow_dispatch:

jobs:
  ingest:
    name: ETL
    runs-on: ubuntu-latest
    environment: OS
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.IAM_ROLE }}
        aws-region: us-west-2

    - name: Install deps
      run: |
        npm install

    - name: Run ETL
      env:
        OS_ENDPOINT: ${{ secrets.OS_ENDPOINT }}
      run: |
        npm run etl
